### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by silikidi** [pudyasto/simmutu#2]
Sebelumnya apresiasi besar buat @pudyasto kontribusinya sangat berharga!
Adakah rencana untuk support PHP 7?
Atau mungkin solusi aplikasi ini bisa berjalan baik di php 7?
Terima kasih

**Comment by pudyasto** [comment]
Terima kasih sebelumnya,
Kebetulan saya pake framework codeigniter, harusnya sih support di PHP 7 mas.
