### ISSUE TITLE
forbiden

### ISSUE THREAD

**Issue by adykazama** [pudyasto/simmutu#4]
![image](https://user-images.githubusercontent.com/26812159/176372675-bf5ab459-a4c8-42b8-89f8-3fa53a3e6307.png)

**Comment by pudyasto** [comment]
Silahkan baca readme.

- Gunakan VirtualHost dan arahkan ke folder public/

https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-20-04
